version: '3.4'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./octo:/app

  database:
    image: mysql:5.7.31
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "octo"
